### ISSUE TITLE
OnePassword not available

### ISSUE THREAD

**Issue by lucascaton** [DriveWealth/react-native-onepassword#3]
Hi there,

I do have 1Password app installed on my iPhone. However, it says I don't.

This is the code I'm using:

```jsx
import React, { Component } from 'react';
import { AppRegistry, StyleSheet, View, Button } from 'react-native';

export default class MyApp extends Component {
  op() {
    var OnePassword = require("react-native-onepassword");

    OnePassword.isSupported().then(
      () => { console.log("OnePassword app is installed and ready!") },
      () => { console.log("OnePassword not available."); }
    );
  }

  render() {
    return <View style={styles.container}>
      <Button onPress={this.op} title="1Password" />
    </View>;
  }
}

const styles = StyleSheet.create({
  container: { flex: 1, justifyContent: 'center', alignItems: 'center', backgroundColor: '#F5FCFF', }
});

AppRegistry.registerComponent('MyApp', () => MyApp);
```

package.json:

```json
{
	(...)
	"dependencies": {
		"react": "~15.4.0",
		"react-native": "0.41.2",
		"react-native-onepassword": "^1.0.4"
	},
	"devDependencies": {
		"babel-jest": "18.0.0",
		"babel-preset-react-native": "1.9.1",
		"jest": "18.1.0",
		"react-test-renderer": "~15.4.0"
	}
}
```

* Xcoode `8.2.1`
* iOS `10.2.1`

Is it a bug?

Thank you.

**Comment by sreucherand** [comment]
Hi,
I had the same issue. First make sure you linked the library to you xCode project.
I would advice you to follow the manual linking procedure here:
https://facebook.github.io/react-native/docs/linking-libraries-ios.html#manual-linking

Then, add the custom URL scheme, `org-appextension-feature-password-management` in your target's `info.plist` as mentioned here:
https://github.com/AgileBits/onepassword-app-extension#use-case-1-native-app-login

Hope it could help!

**Comment by jjshammas** [comment]
Looks like this is no longer an issue. Let me know if otherwise

**Comment by AhadCove** [comment]
I'm actually having this same issue. I manually linked it and everything. When I pulled up ```Onepassword.xcodeproj``` I see that it has this error:
`'React/RCTBridgeModule.h' file not found`

and this is the line bringing up the error:

`#import <React/RCTBridgeModule.h>`

**Comment by AhadCove** [comment]
I got past the file not found issue, but still receiving `OnePassword not available`

**Comment by joeybaker** [comment]
@AhadCove Make sure you add the following to your `Info.plist`

```xml
	<key>LSApplicationQueriesSchemes</key>
	<array>
		<string>org-appextension-feature-password-management</string>
	</array>
```

**Comment by AhadCove** [comment]
@joeybaker I just tried this and still not available
